services:

  
  db:
    image: postgres:16

    container_name: postgres_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobtracker

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    container_name: job_tracker_api

    ports:
      - "8000:8000"


    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/jobtracker
      SECRET_KEY: lakhvir123

    

volumes:
  postgres_data: